# Generated by Django 6.0.4 on 2026-04-09 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CTScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(max_length=500, upload_to='ct_scans/original/')),
                ('preprocessed_path', models.CharField(blank=True, max_length=500, null=True)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('preprocessing', 'Preprocessing'), ('analyzed', 'Analyzed'), ('validated', 'Validated'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('patient', models.ForeignKey(help_text='The patient this scan belongs to', limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_scans', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(help_text='User who performed the upload (patient, nurse, or lab_tech)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans_uploaded_by_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ct_scans',
                'ordering': ['-upload_timestamp'],
            },
        ),
    ]
