# Generated by Django 6.0.4 on 2026-04-09 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_class', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], max_length=20)),
                ('confidence_score', models.FloatField(help_text='0.0 to 1.0')),
                ('ai_timestamp', models.DateTimeField(auto_now_add=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('corrected', 'Corrected'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_ai_results', to=settings.AUTH_USER_MODEL)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_result', to='diagnostics.ctscan')),
            ],
            options={
                'db_table': 'ai_results',
                'ordering': ['-ai_timestamp'],
            },
        ),
    ]
